name: shell_comands

on: [push,pull_request ]

jobs:
  run-shell-command: #name of the job
    runs-on: ubuntu-latest  #os or the base image on which the job should run
    steps:
      - name: first step
        run: echo "Hello world"
      - name: second step 
        run: |
          node -v
          npm -v    
