name: multiple_shell_executors
on: [push]
jobs:
  multiple_shell_executors:
    runs-on: ubuntu-latest
    steps:
      - name: shell_script 
        run: |
          sudo apt install vim
          sudo apt install git
      - name: python_script
        run: |
          import platform
          print(platform.processor())
        shell: python 
  multiple_shell_windows:
    runs-on: windows-latest
    needs: ["multiple_shell_executors"]
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: working_directory
        run: pwd
        shell: bash  
